from __future__ import annotations

import struct
import zlib
from pathlib import Path

import pymupdf

FIXTURE_TEXT_LICENSE = "CC0-1.0; text and graphics generated by the pdf2epub project"


def _png_chunk(kind: bytes, data: bytes) -> bytes:
    return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", zlib.crc32(kind + data))


def generated_png(width: int = 96, height: int = 64) -> bytes:
    rows = bytearray()
    for y in range(height):
        rows.append(0)
        for x in range(width):
            rows.extend((40 + x * 180 // width, 80 + y * 120 // height, 170))
    return (
        b"\x89PNG\r\n\x1a\n"
        + _png_chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0))
        + _png_chunk(b"IDAT", zlib.compress(bytes(rows), 9))
        + _png_chunk(b"IEND", b"")
    )


def _metadata(title: str) -> dict[str, str]:
    return {
        "title": title,
        "author": "pdf2epub fixture generator",
        "subject": FIXTURE_TEXT_LICENSE,
        "creator": "pdf2epub",
        "producer": "PyMuPDF",
        "creationDate": "D:20260816000000+08'00'",
        "modDate": "D:20260816000000+08'00'",
    }


def _save(document: pymupdf.Document, path: Path, title: str) -> None:
    document.set_metadata(_metadata(title))
    document.save(path, garbage=4, deflate=True)
    document.close()


def make_single_column(path: Path) -> None:
    document = _single_column_document()
    _save(document, path, "Digital Single Column")


def _single_column_document() -> pymupdf.Document:
    document = pymupdf.open()
    page = document.new_page(width=612, height=792)
    page.insert_text((72, 72), "Chapter 1", fontsize=22, fontname="hebo")
    page.insert_textbox(
        pymupdf.Rect(72, 105, 540, 180),
        "A Small Digital Book\nThis fixture contains selectable English text and stable geometry.",
        fontsize=12,
        fontname="tiro",
        lineheight=1.35,
    )
    page.insert_text(
        (72, 215), "The conversion engine keeps the original text and its coordinates.", fontsize=11
    )
    page.insert_text((72, 232), "A normalized copy can repair a repeat-", fontsize=11)
    page.insert_text(
        (72, 249), "able line break without overwriting the raw extraction.", fontsize=11
    )
    page.insert_text(
        (72, 285), "A second paragraph gives the exporter enough content to reflow.", fontsize=11
    )
    return document


def _rasterized_single_page() -> tuple[bytes, float, float]:
    source = _single_column_document()
    try:
        page = source[0]
        pixmap = page.get_pixmap(dpi=200, alpha=False)
        return pixmap.tobytes("png"), page.rect.width, page.rect.height
    finally:
        source.close()


def make_scanned_only(path: Path) -> None:
    image, width, height = _rasterized_single_page()
    document = pymupdf.open()
    page = document.new_page(width=width, height=height)
    page.insert_image(page.rect, stream=image)
    _save(document, path, "Scanned Only")


def make_mixed(path: Path) -> None:
    digital = _single_column_document()
    scanned_image, width, height = _rasterized_single_page()
    scanned = pymupdf.open()
    scanned_page = scanned.new_page(width=width, height=height)
    scanned_page.insert_image(scanned_page.rect, stream=scanned_image)
    document = pymupdf.open()
    document.insert_pdf(digital)
    document.insert_pdf(scanned)
    digital.close()
    scanned.close()
    _save(document, path, "Mixed Digital and Scanned")


def make_hidden_text_layer(path: Path) -> None:
    image, width, height = _rasterized_single_page()
    document = pymupdf.open()
    page = document.new_page(width=width, height=height)
    page.insert_image(page.rect, stream=image)
    page.insert_text(
        (72, 72),
        "Hidden accessible text layer with enough characters to remain usable for native parsing "
        "without invoking OCR.",
        fontsize=11,
        render_mode=3,
    )
    _save(document, path, "Image With Hidden Text Layer")


def make_suspect(path: Path) -> None:
    image, _width, _height = _rasterized_single_page()
    document = pymupdf.open()
    page = document.new_page(width=612, height=792)
    page.insert_image(pymupdf.Rect(0, 0, 612, 500), stream=image, keep_proportion=False)
    page.insert_text((72, 550), "Tiny text", fontsize=8)
    _save(document, path, "Suspect Native Layer")


def make_blank(path: Path) -> None:
    document = pymupdf.open()
    document.new_page(width=612, height=792)
    _save(document, path, "Blank Page")


def make_rotated_scanned(path: Path) -> None:
    image, width, height = _rasterized_single_page()
    document = pymupdf.open()
    page = document.new_page(width=width, height=height)
    page.insert_image(page.rect, stream=image)
    page.set_rotation(90)
    _save(document, path, "Rotated Scanned Page")


def make_large_boundary(path: Path) -> None:
    document = pymupdf.open()
    page = document.new_page(width=1550, height=2000)
    page.insert_text((150, 180), "Large generated page boundary fixture", fontsize=28)
    _save(document, path, "Large Boundary Page")


def make_two_column(path: Path) -> None:
    document = pymupdf.open()
    page = document.new_page(width=612, height=792)
    page.insert_text((72, 65), "Two Column Reading Order", fontsize=20, fontname="hebo")
    left = [
        "Left column begins first.",
        "Its second line follows.",
        "Its final line ends here.",
    ]
    right = [
        "Right column begins later.",
        "Its second line follows.",
        "Its final line ends here.",
    ]
    for index, text in enumerate(left):
        page.insert_text((72, 120 + index * 22), text, fontsize=11)
    for index, text in enumerate(right):
        page.insert_text((330, 120 + index * 22), text, fontsize=11)
    _save(document, path, "Digital Two Column")


def make_image_caption(path: Path) -> None:
    document = pymupdf.open()
    page = document.new_page(width=612, height=792)
    page.insert_text((72, 70), "A Figure", fontsize=20, fontname="hebo")
    page.insert_text((72, 110), "The text before the figure remains in reading order.", fontsize=11)
    page.insert_image(pymupdf.Rect(156, 150, 456, 350), stream=generated_png())
    page.insert_text(
        (180, 375), "Figure 1. A generated public-domain gradient.", fontsize=10, fontname="heit"
    )
    page.insert_text(
        (72, 420), "The paragraph after the figure also remains available.", fontsize=11
    )
    _save(document, path, "Digital Image and Caption")


def make_structure_edges(path: Path) -> None:
    document = pymupdf.open()
    first = document.new_page(width=612, height=792)
    first.insert_text((220, 35), "Fixture Header", fontsize=9)
    first.insert_text((72, 75), "Cross-page Structure", fontsize=20, fontname="hebo")
    first.insert_text(
        (72, 130), "This paragraph starts on the first page and deliberately", fontsize=11
    )
    first.insert_text((72, 147), "continues after the page boundary", fontsize=11)
    first.insert_text((300, 760), "1", fontsize=9)
    second = document.new_page(width=612, height=792)
    second.insert_text((220, 35), "Fixture Header", fontsize=9)
    second.insert_text(
        (72, 75), "without pretending that M1 solves every cross-page case.", fontsize=11
    )
    second.insert_text(
        (72, 115), "The raw text is still preserved for later correction.", fontsize=11
    )
    second.insert_text((300, 760), "2", fontsize=9)
    third = document.new_page(width=612, height=792)
    third.set_rotation(90)
    third.insert_text((72, 90), "A rotated page is flagged for review.", fontsize=11)
    _save(document, path, "Digital Structure Edges")


def make_hundred_pages(path: Path) -> None:
    document = pymupdf.open()
    for number in range(1, 101):
        page = document.new_page(width=612, height=792)
        page.insert_text((72, 70), f"Page {number}", fontsize=18, fontname="hebo")
        page.insert_text(
            (72, 115),
            f"This is generated page {number} of the non-blocking GUI fixture.",
            fontsize=11,
        )
    _save(document, path, "Digital One Hundred Pages")


def generate_fixture_corpus(output: Path) -> list[Path]:
    output.mkdir(parents=True, exist_ok=True)
    makers = {
        "digital_single_column.pdf": make_single_column,
        "digital_two_column.pdf": make_two_column,
        "digital_image_caption.pdf": make_image_caption,
        "digital_structure_edges.pdf": make_structure_edges,
        "digital_100_pages.pdf": make_hundred_pages,
        "scanned_only.pdf": make_scanned_only,
        "mixed.pdf": make_mixed,
        "image_hidden_text_layer.pdf": make_hidden_text_layer,
        "suspect_native_layer.pdf": make_suspect,
        "blank.pdf": make_blank,
        "rotated_scanned.pdf": make_rotated_scanned,
        "large_boundary.pdf": make_large_boundary,
    }
    generated = []
    for name, maker in makers.items():
        path = output / name
        maker(path)
        generated.append(path)
    (output / "LICENSE.txt").write_text(
        f"{FIXTURE_TEXT_LICENSE}\nNo third-party book text is included.\n", encoding="utf-8"
    )
    return generated
